# Auto-generated with `stubgen -m spatial_transformation.cpp`
# Needs to be updated manually if there are changes in the cpp module!
from typing import List

from typing import overload
import numpy

class Transformation:
    translation: numpy.ndarray[numpy.float64[3, 1]]
    def __init__(self) -> None: ...
    def apply(
        self, arg0: numpy.ndarray[numpy.float64[3, 1]]
    ) -> numpy.ndarray[numpy.float64[3, 1]]: ...
    def get_rotation(self) -> List[float[4]]: ...
    def inverse(self) -> Transformation: ...
    def matrix(self) -> numpy.ndarray[numpy.float64[4, 4]]: ...
    def set_rotation(self, arg0: List[float[4]]) -> None: ...
    @overload
    def __mul__(self, arg0: Transformation) -> Transformation: ...
    @overload
    def __mul__(
        self, arg0: numpy.ndarray[numpy.float64[3, 1]]
    ) -> numpy.ndarray[numpy.float64[3, 1]]: ...
